---
# tasks file for ansible-osx-command-line-tools

- name: Am I running on Mac OS X?
  assert:
    that: ansible_distribution == 'MacOSX'
    msg: Target host is not running Mac OS X

- name: Remove existing Command Line Tools installation
  file:
    path: '{{ clt_path }}'
    state: absent
  when: clt_force_install
  become: yes

- name: Check that the Command Line Tools path is present
  stat:
    path: '{{ clt_path }}'
  register: clt

- name: Is the C++ compiler useable?
  command: g++ --version
  register: compiler
  check_mode: no
  ignore_errors: true
  changed_when: false

- name: Check the Command Line Tools package metadata
  command: pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
  register: pkg_info
  check_mode: no
  ignore_errors: true
  changed_when: false

- name: Install if Command Line Tools detection failed
  include_tasks: install_clt.yml
  when: pkg_info.rc != 0 or compiler.rc != 0 or not clt.stat.exists
